// Dishes
export const GET_DISHES = 'GET_DISHES';
export const ADD_DISH = 'ADD_DISH';
export const REMOVE_DISH = 'REMOVE_DISH';

// Ingredient
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

// Ingredient
export const ADD_DISH_CATEGORY = 'ADD_DISH_CATEGORY';
export const REMOVE_DISH_CATEGORY = 'REMOVE_DISH_CATEGORY';
export const ADD_INGREDIENT_CATEGORY = 'ADD_INGREDIENT_CATEGORY';
export const REMOVE_INGREDIENT_CATEGORY = 'REMOVE_INGREDIENT_CATEGORY';

// Shopping Cart
export const GET_CART = 'GET_CART';
export const GET_DISHES_COUNT = 'GET_DISHES_COUNT';
export const ADD_DISH_TO_CART = 'ADD_DISH_TO_CART';
export const REMOVE_DISH_FROM_CART = 'REMOVE_DISH_FROM_CART';